import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier';

// Flat config (ESLint 9). eslint-config-next 16 ships native flat configs, so we
// spread them directly — the old FlatCompat wrapper around them crashes the
// config validator in v16 (circular structure). `prettier` (eslint-config-prettier)
// turns off rules that conflict with Prettier and must come last.
const config = [
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'src/generated/**',
      'prisma/migrations/**',
      'playwright-report/**',
      'test-results/**',
      // Auto-generated by Next; not ours to lint (matches `next lint`).
      'next-env.d.ts',
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  prettier,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      // New react-hooks rules introduced by eslint-config-next 16. Most hits are
      // legitimate "sync state to props" / ref patterns; demoted to warnings so
      // the Next 16 bump stays clean. Tracked as a follow-up cleanup (not blocking).
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
    },
  },
  {
    // Root config files run in Node and legitimately use require()/CJS idioms.
    files: ['*.config.{js,cjs,mjs,ts}'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
];

export default config;
