import 'server-only';
import { ActionItemStatus, GoalStatus } from '@prisma/client';
import { prisma } from '@/lib/db/prisma';
import type { MeetingPrepContext, MeetingPrepResult } from './prepare';

// Gathers the real records behind the AI meeting-prep view (experience-layer.md
// §1.5) and exposes the per-meeting cache. Participant-only: the meeting's mentor
// or mentee. The AI suggestion itself is generated by the action and cached on the
// meeting row.

const GOALS_TO_REVIEW: GoalStatus[] = [GoalStatus.SUBMITTED, GoalStatus.APPROVED, GoalStatus.COMPLETED];

export interface MeetingPrepView {
  meeting: {
    id: string;
    title: string;
    type: string;
    startsAt: Date | null;
    cohortId: string;
    menteeId: string;
  };
  viewerRole: 'mentor' | 'mentee';
  context: MeetingPrepContext;
  cached: MeetingPrepResult | null;
  generatedAt: Date | null;
}

/** Load a meeting + assembled prep context for a participant, or null if the
 *  meeting is missing or the user is not a participant. */
export async function getMeetingPrep(
  meetingId: string,
  userId: string,
): Promise<MeetingPrepView | null> {
  const meeting = await prisma.meeting.findUnique({
    where: { id: meetingId },
    include: { mentor: { select: { name: true } }, mentee: { select: { name: true } } },
  });
  if (!meeting || meeting.deletedAt) return null;

  const isMentor = meeting.mentorId === userId;
  const isMentee = meeting.menteeId === userId;
  if (!isMentor && !isMentee) return null;

  const [lastLog, pendingItems, goals] = await Promise.all([
    prisma.sessionLog.findFirst({
      where: { mentorId: meeting.mentorId, menteeId: meeting.menteeId, deletedAt: null },
      orderBy: { date: 'desc' },
      select: { date: true, aiSummary: true, discussionSummary: true },
    }),
    prisma.actionItem.findMany({
      where: {
        deletedAt: null,
        status: { not: ActionItemStatus.DONE },
        sessionLog: { mentorId: meeting.mentorId, menteeId: meeting.menteeId },
      },
      orderBy: { createdAt: 'asc' },
      take: 10,
      include: { assignee: { select: { name: true } } },
    }),
    prisma.goal.findMany({
      where: { menteeId: meeting.menteeId, deletedAt: null, status: { in: GOALS_TO_REVIEW } },
      orderBy: { createdAt: 'desc' },
      take: 10,
      select: { title: true },
    }),
  ]);

  const context: MeetingPrepContext = {
    meetingTitle: meeting.title,
    meetingType: meeting.type,
    counterpartName: isMentor ? meeting.mentee.name : meeting.mentor.name,
    previousSessionSummary: lastLog ? (lastLog.aiSummary || lastLog.discussionSummary || null) : null,
    previousSessionDate: lastLog?.date ? lastLog.date.toISOString().slice(0, 10) : null,
    pendingActionItems: pendingItems.map((a) => ({
      title: a.title,
      owner: a.assignee?.name ?? null,
      due: a.dueDate ? a.dueDate.toISOString().slice(0, 10) : null,
      status: a.status,
    })),
    goalTitles: goals.map((g) => g.title),
  };

  return {
    meeting: {
      id: meeting.id,
      title: meeting.title,
      type: meeting.type,
      startsAt: meeting.startsAt,
      cohortId: meeting.cohortId,
      menteeId: meeting.menteeId,
    },
    viewerRole: isMentor ? 'mentor' : 'mentee',
    context,
    cached: (meeting.prepJson as MeetingPrepResult | null) ?? null,
    generatedAt: meeting.prepGeneratedAt,
  };
}
